pip install selenium
pip install xlrd
pip install pymysql
pip install lxml
pip install Pillow
pip install win32gui
pip install win32con
pip install requests
pip install qrcode
pip install pexpect
pip install chinesecalendar
pip install automagica
pip install tushare
pip install imapclient
pip install pymysql
pip install schedule
pip install paramiko
pip install pypiwin32
pip install pdfminer3K
pip install browsermob-proxy
pip install pywin32
pip install python-dateutil
pip install bs4
pip install configparser
pip install beautifulsoup4
pip install html5lib
pip install matplotlib
python -m pip install cx_Oracle --upgrade
pip install sqlparse
pip install DBUtils
pip install keyboard
pip install aircv
pip install opencv-python